name: kmeans-glacier
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - geopandas
  - rasterio
  - scikit-image
  - shapely
  - joblib
  - earthengine-api
